import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { SessionProvider } from 'next-auth/react';
import { PostProvider } from '../context';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import NextAuthProvider from '../NextAuthProvider';
import { auth } from '@/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // const session = await auth();
  const messages = useMessages();

  return (
    <NextAuthProvider>
      <html lang={locale}>
        <body className={inter.className}>
          <PostProvider>
            <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
            </NextIntlClientProvider>
          </PostProvider>
        </body>
      </html>
    </NextAuthProvider>
  );
}
